### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ricefish888** [Bonitasoft-Community/Build-Bonita#30] opened 2019-10-29 18:41 UTC
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.784 s
[INFO] Finished at: 2019-10-29T11:41:02-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (yarn build) on project bonita-portal-js: Failed to run task: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (yarn build) on project bonita-portal-js: Failed to run task

**Comment by tbouffard** [comment] 2019-10-30 10:42
@ricefish888 can you provide more error logs please and info about your environment (os, jvm, ...)? we cannnot investigate on your issue without that
thanks

**Comment by ricefish888** [comment] 2019-10-30 11:35
ubuntu 18.04  jdk1.8

There was an error compiling bonita-portal-js, no more logs.

**Comment by amottier** [comment] 2019-10-30 12:52
Can you try to run again the build with the following command: `bash build-script.sh 2>&1 | tee bonita-build-01.log` and share the `bonita-build-01.log` it will create?

**Comment by ricefish888** [comment] 2019-10-30 13:55
bonita-build-01.log


[[1;34mINFO[m] 
[[1;34mINFO[m] > portaljs@0.0.0 prebuild:less /home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js
[[1;34mINFO[m] > mkdirp target/css
[[1;34mINFO[m] 
[[1;34mINFO[m] 
[[1;34mINFO[m] > portaljs@0.0.0 build:less /home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js
[[1;34mINFO[m] > lessc main/styles/main.less > target/css/bonita-skin.css
[[1;34mINFO[m] 
[[1;34mINFO[m] [31m>> [39mTasks directory "tasks" not found.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "newer:jshint" (newer) task[24m
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "newer:jshint:all" (newer) task[24m
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "jshint:all" (jshint) task[24m
[[1;34mINFO[m] [32m>> [39m113 files lint free.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "newer-postrun:jshint:all:1:/home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/node_modules/grunt-newer/.cache" (newer-postrun) task[24m
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "newer:jshint:test" (newer) task[24m
[[1;34mINFO[m] No newer files to process.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "html2js:main" (html2js) task[24m
[[1;34mINFO[m] Successfully converted [32m56[39m html templates to js.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "clean:server" (clean) task[24m
[[1;34mINFO[m] Cleaning .tmp...[32mOK[39m
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "clean:test" (clean) task[24m
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "concurrent:test" (concurrent) task[24m
[[1;34mINFO[m]     
[[1;34mINFO[m]     [31m>> [39mTasks directory "tasks" not found.
[[1;34mINFO[m]     
[[1;34mINFO[m]     [4mRunning "copy:styles" (copy) task[24m
[[1;34mINFO[m]     Copied [36m1[39m files
[[1;34mINFO[m]     
[[1;34mINFO[m]     [32mDone, without errors.[39m
[[1;34mINFO[m]     
[[1;34mINFO[m]     
[[1;34mINFO[m]     Execution Time (2019-10-30 13:51:24 UTC)
[[1;34mINFO[m]     loading tasks  41ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75%
[[1;34mINFO[m]     copy:styles    13ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 24%
[[1;34mINFO[m]     Total 55ms
[[1;34mINFO[m]     
[[1;34mINFO[m] [4mRunning "autoprefixer:dist" (autoprefixer) task[24m
[[1;34mINFO[m] Prefixed file ".tmp/styles/bonita-theme.css" created.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "connect:test" (connect) task[24m
[[1;34mINFO[m] Started connect web server on 127.0.0.1:9001.
[[1;34mINFO[m] 
[[1;34mINFO[m] [4mRunning "karma:unit" (karma) task[24m
[[1;34mINFO[m] [32m30 10 2019 13:51:29.561:INFO [karma]: [39mKarma v0.13.21 server started at http://localhost:8988/
[[1;34mINFO[m] [32m30 10 2019 13:51:29.574:INFO [launcher]: [39mStarting browser PhantomJS
[[1;34mINFO[m] [32m30 10 2019 13:51:30.286:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: [39mConnected on socket hBdx0oNICQ14k5GzAAAA with id 45701112
[[1;34mINFO[m] .......................
[[1;34mINFO[m] WARN: 'Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.'
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] .....................................................................
[[1;34mINFO[m] PhantomJS 2.1.1 (Linux 0.0.0) Directive: backButton should call back history on click FAILED
[[1;34mINFO[m] 	TypeError: Attempted to assign to readonly property. in /home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/test/spec/features/admin/applications/details/application-details.spec.js (line 243)
[[1;34mINFO[m] 	/home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/test/spec/features/admin/applications/details/application-details.spec.js:243:14
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] ..............[33m30 10 2019 13:51:33.669:WARN [web-server]: [39m404: /API/avatars/139
[[1;34mINFO[m] ..................................................................
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] .........................................[33m30 10 2019 13:51:34.619:WARN [web-server]: [39m404: /base/dev/fixtures/form.html
[[1;34mINFO[m] [33m30 10 2019 13:51:34.620:WARN [web-server]: [39m404: /base/dev/fixtures/form.html?tata&toto
[[1;34mINFO[m] ..
[[1;34mINFO[m] PhantomJS 2.1.1 (Linux 0.0.0) iframe directive should compute params FAILED
[[1;34mINFO[m] 	Error: Expected a spy, but got Function. in /home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2600)
[[1;34mINFO[m] 	/home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/test/spec/features/user/tasks/list/common/directive/bonitaFormViewer.spec.js:46:71
[[1;34mINFO[m] PhantomJS 2.1.1 (Linux 0.0.0) iframe directive should update frameUrl and switching param when url change FAILED
[[1;34mINFO[m] 	Error: Expected a spy, but got Function. in /home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2600)
[[1;34mINFO[m] 	/home/rex/Dev/lowCodePlatform/Build-Bonita/bonita-portal-js/test/spec/features/user/tasks/list/common/directive/bonitaFormViewer.spec.js:52:71
[[1;34mINFO[m] ................................................................................
[[1;34mINFO[m] ......................................................
[[1;34mINFO[m] PhantomJS 2.1.1 (Linux 0.0.0): Executed 832 of 832 (3 FAILED) (5.63 secs / 5.583 secs)
[[1;34mINFO[m] Warning: Task "karma:unit" failed. Use --force to continue.
[[1;34mINFO[m] 
[[1;34mINFO[m] Aborted due to warnings.
[[1;34mINFO[m] 
[[1;34mINFO[m] 
[[1;34mINFO[m] Execution Time (2019-10-30 13:51:22 UTC)
[[1;34mINFO[m] jshint:all       983ms  ▇▇▇▇ 7%
[[1;34mINFO[m] concurrent:test   1.5s  ▇▇▇▇▇ 10%
[[1;34mINFO[m] karma:unit       11.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 82%
[[1;34mINFO[m] Total 14.4s
[[1;31mERROR[m] error Command failed with exit code 3.
[[1;34mINFO[m] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  22.053 s
[[1;34mINFO[m] Finished at: 2019-10-30T06:51:36-07:00
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32mcom.github.eirslett:frontend-maven-plugin:1.6:yarn[m [1m(yarn build)[m on project [36mbonita-portal-js[m: [1;31mFailed to run task[m: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by amottier** [comment] 2019-10-30 14:12
Can you:

- Share the full log file
- Provide the id of the commit you checked out for the project `build-bonita`
- Confirm that you are trying to build Bonita 7.9.4

Thanks.

We are able to run this script in different environment including continuous integration and I never saw this `bonita-portal-js` project test failed.

**Comment by tbouffard** [comment] 2019-10-31 09:39
ℹ️ Full bointa-portal-js build by Travis on 7.9.x branch is ok, see https://travis-ci.org/bonitasoft/bonita-portal-js/builds/594548587

**Comment by amottier** [comment] 2019-11-04 11:50
Sorry but I'm still not able to reproduce your issue even on a clean Ubuntu 18.04 LTS setup (in a VM).

Did you do any modifications to the source code of bonita-portal-js?

**Comment by ricefish888** [comment] 2019-11-04 12:29
I have not modified any code.
Are you sure that it is a Build-Bonita master branch?
What is your VM configuration environment?

Thank you!

**Comment by amottier** [comment] 2019-11-04 15:09
I'm using an up to date `master` branch to do my tests.

I did some test on Debian 10 with the following JVM:
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

And on Ubuntu 18.04 LTS (running in in VirtualBox 6.0.14)
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

You can see the configuration of Travis CI in [.travis.yml](https://github.com/Bonitasoft-Community/Build-Bonita/blob/master/.travis.yml) and follow test result from https://travis-ci.org/Bonitasoft-Community/Build-Bonita

**Comment by ricefish888** [comment] 2019-11-04 16:44
PhantomJS has been installed on my computer and is a PhantomJS version issue.

However, why is the bonita-ui-designer angularjs version still 1.4? Not updated to angular 8 or other newer versions?

Thank you very much for your answer!

**Comment by amottier** [comment] 2019-11-04 17:34
Do you mean that the issue was a conflict between the PhantomJS installed locally on your computer and the one provided in bonita-portal-js project?
Can you confirm that you can now successfully build Bonita?

**Comment by ricefish888** [comment] 2019-11-04 17:36
Yes, there are conflicts.
It has been successfully built.

**Comment by amottier** [comment] 2019-11-04 17:45
Thanks for the feedback, I will now close this issue.

Regarding your point about AngularJS version we stick with version 1.4 because our users and clients build user interface with Bonita UI Designer that is based on this version and automated the migration to a newer version of Angular is not doable.

**Closed by amottier** 2019-11-04 17:45 UTC
Labels: question
